//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blockchain.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunler()
        {
            this.kullaniciUrunler = new HashSet<kullaniciUrunler>();
        }
    
        public int urunId { get; set; }
        public string urunName { get; set; }
        public Nullable<int> fiyat { get; set; }
        public Nullable<int> kategori { get; set; }
        public Nullable<int> miktar { get; set; }
        public string userName { get; set; }
    
        public virtual kategori kategori1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullaniciUrunler> kullaniciUrunler { get; set; }
    }
}
